FROM golang:1.20.5 as builder

WORKDIR /src
COPY . .
ARG TARGETARCH
ARG TARGETOS

RUN go get && CGO_ENABLED=0 GOOS=${TARGETOS} GOARCH=${TARGETARCH} go build -v -o job


FROM scratch
WORKDIR /
COPY --from=builder /src/job .
ENTRYPOINT ["/job"]