kind: Deployment
apiVersion: apps/v1
metadata:
  name: aks-demo-job
  namespace: aks-demo
  labels:
    app: aks-demo-job
spec:
  replicas: 1
  selector:
    matchLabels:
      app: aks-demo-job
  template:
    metadata:
      labels:
        app: aks-demo-job
    spec:
      containers:
        - name: aks-demo-job
          image: dletnikov/aks-demo-job:v1.0.0-8eb6cd3-linux-amd64
          volumeMounts:
            - name: secrets-store01-inline
              mountPath: "/mnt/secrets-store"
              readOnly: true
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          imagePullPolicy: IfNotPresent
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      securityContext: {}
      schedulerName: default-scheduler
      volumes:
        - name: secrets-store01-inline
          csi:
            driver: secrets-store.csi.k8s.io
            readOnly: true
            volumeAttributes:
              secretProviderClass: "aks-demo-secret-class"
