FROM golang:1.20.5 as builder

WORKDIR /src
COPY . .
ARG TARGETARCH
ARG TARGETOS

RUN go get && CGO_ENABLED=0 GOOS=${TARGETOS} GOARCH=${TARGETARCH} go build -v -o bot


FROM scratch
WORKDIR /
COPY --from=builder /src/bot .
COPY --from=alpine:latest /etc/ssl/certs/ca-certificates.crt /etc/ssl/certs/
ENTRYPOINT ["/bot", "start"]