name: AKS-DEMO-JOB-CICD

on:
  push:
    branches:
      - main
    paths:
      - job/main.go

permissions:
  contents: write

jobs:
  ci:
     name: CI
     runs-on: ubuntu-latest
     
     steps:
       - name: Checkout
         uses: actions/checkout@v2
         with:
           fetch-depth: 0 

#       - name: Run test
#         run: make test

       - name: Login to Docker Hub
         uses: docker/login-action@v1
         with:
           username: ${{ secrets.DOCKERHUB_USERNAME }}
           password: ${{ secrets.DOCKERHUB_TOKEN }}

       - name: Build&Push
         run: make job-image job-push
  cd:
     name: CD
     needs: ci
     runs-on: ubuntu-latest
          
     steps:

     - uses: actions/checkout@v2
       with:
         fetch-depth: 0
     - run: echo "VERSION=$(git describe --tags --abbrev=0)-$(git rev-parse --short HEAD)" >> $GITHUB_ENV

     - uses: mikefarah/yq@master
       with:
         cmd: yq -i '.spec.template.spec.containers[0].image = "dletnikov/aks-demo-job:" + strenv(VERSION) + "-linux-amd64"' clusters/flux-system/job/aks-demo-job-deploy.yaml


     - run: |
         git config user.name github-actions
         git config user.email github-actions@github.com
         git commit -am "update version $VERSION"
         git push
